version: '3.8'

services:

  mariadb:
    image: mariadb:latest
    container_name: mysql-ski-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ski_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  setup:
    build:
      context: .
      dockerfile: DockerFile
    depends_on:
      - mariadb
  

volumes:
  db_data: