FROM python:3.13-slim

RUN apt-get update && \
    apt-get install -y gcc libmariadb-dev && \
    pip install mariadb 

WORKDIR /db-init

COPY scheme.sql .
COPY sample_data.sql .
COPY setup.py .

CMD ["python3", "setup.py"]